name: Deploy
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          git config --global user.email "roy@segall.io"
          git config --global user.name "Roy segall"
      - run: npm install
      - run: npm run build
      - run: npm run deploy
