name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          git config --global user.email "roy@segall.io"
          git config --global user.name "Roy segall"
      - run: npm install
      - run: npm run build
      - name: Deploy with gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RoySegall/stomli.git
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
